### ISSUE TITLE
OpenSearch Bulk error doesn't contain "create" key

### ISSUE THREAD

**Issue by lambda-science** [deepset-ai/haystack-core-integrations#547]
**Describe the bug**
When calling `write_documents` from OpenSearch vector store, if something goes wrong the error is treated with this line:
```python
        if errors:
            duplicate_errors_ids = []
            other_errors = []
            for e in errors:
                error_type = e["create"]["error"]["type"]
```
https://github.com/deepset-ai/haystack-core-integrations/blob/4998a7a6d840070d87f838c73cdf9010aba16865/integrations/opensearch/src/haystack_integrations/document_stores/opensearch/document_store.py#L184

However today in production I come across a problem with `write_documents` and the `bulk` funciton where the error code doesn't actually contains the `"create"` key.

CloudWatch (AWS) logs:
```
2024-03-06T09:10:38.444+01:00 Creating embeddings: 100%\|██████████\| 1/1 [00:00<00:00,  1.02it/s]

2024-03-06T09:10:38.475+01:00 03/06/2024 08:10:38 AM 'create'
```
**To Reproduce**
No idea how to reproduce as I don't have the real error due to this logic.

**Describe your environment (please complete the following information):**
 - OS: Ubuntu Docker Container
 - Haystack version: 2.0 beta 8
 - Integration version: OpenSearch v0.2.0

**Comment by lambda-science** [comment]
Better traceback
```python
2024-03-06T12:44:22.794+01:00 | Creating embeddings: 0%\| \| 0/1 [00:00<?, ?it/s] Creating embeddings: 100%\|██████████\| 1/1 [00:00<00:00, 2.42it/s] Creating embeddings: 100%\|██████████\| 1/1 [00:00<00:00, 2.42it/s]
  | 2024-03-06T12:44:22.827+01:00 | 03/06/2024 11:44:22 AM Traceback (most recent call last):
  | 2024-03-06T12:44:22.827+01:00 | File "/code/haystack_api/controller/file_upload.py", line 174, in index_file_task
  | 2024-03-06T12:44:22.827+01:00 | result = indexing_pipeline.run(
  | 2024-03-06T12:44:22.827+01:00 | ^^^^^^^^^^^^^^^^^^^^^^
  | 2024-03-06T12:44:22.827+01:00 | File "/usr/local/lib/python3.12/site-packages/haystack/core/pipeline/pipeline.py", line 771, in run
  | 2024-03-06T12:44:22.827+01:00 | res = comp.run(**last_inputs[name])
  | 2024-03-06T12:44:22.827+01:00 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | 2024-03-06T12:44:22.827+01:00 | File "/usr/local/lib/python3.12/site-packages/haystack/components/writers/document_writer.py", line 84, in run
  | 2024-03-06T12:44:22.827+01:00 | documents_written = self.document_store.write_documents(documents=documents, policy=policy)
  | 2024-03-06T12:44:22.827+01:00 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | 2024-03-06T12:44:22.827+01:00 | File "/usr/local/lib/python3.12/site-packages/haystack_integrations/document_stores/opensearch/document_store.py", line 171, in write_documents
  | 2024-03-06T12:44:22.827+01:00 | error_type = e["create"]["error"]["type"]
  | 2024-03-06T12:44:22.827+01:00 | ~^^^^^^^^^^
  | 2024-03-06T12:44:22.827+01:00 | KeyError: 'create'
  | 2024-03-06T12:44:22.827+01:00 | 03/06/2024 11:44:22 AM 'create'

```

**Comment by lambda-science** [comment]
So the fix works and now I can track the real errors. Maybe I should create a separate issue for when my document writing fails ?
`03/06/2024 01:19:32 PM Failed to write documents to OpenSearch. Errors:`
```json
[
   {
      "index":{
         "_index":"pythia",
         "_id":"eb2b7601cebb69ae49d1f293dbc6f7571d1c400feaa83db1975454eba52d721c",
         "status":400,
         "error":{
            "type":"mapper_parsing_exception",
            "reason":"failed to parse field [embedding] of type [knn_vector] in document with id 'eb2b7601cebb69ae49d1f293dbc6f7571d1c400feaa83db1975454eba52d721c'. Preview of field's value: '[-0.005344391, 0.02192688, -0.003829956, ...  -0.030273438]'",
            "caused_by":{
               "type":"illegal_state_exception",
               "reason":"Indexing knn vector fields is rejected as circuit breaker triggered. Check _opendistro/_knn/stats for detailed state"
            }
         }
      }
   }
]
```
