### ISSUE TITLE
OllamaDocumentEmbedder fails with requests.exceptions.JSONDecodeError: Extra data

### ISSUE THREAD

**Issue by cythaletheon** [deepset-ai/haystack-core-integrations#886]
**Describe the bug**
Running the example for Document embedding via an Ollama server that is present within the source shown in github here (https://github.com/deepset-ai/haystack-core-integrations/blob/main/integrations/ollama/src/haystack_integrations/components/embedders/ollama/document_embedder.py) results in a failure on line 139 of document_embedder.py:
###########################################################
Calculating embeddings:   0%|                                                                                                                     | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/d/Development_Source/app/.venv/lib/python3.10/site-packages/requests/models.py", line 963, in json
    return complexjson.loads(self.content.decode(encoding), **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 98)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/d/Development_Source/app/testollama.py", line 19, in <module>
    result = document_embedder.run([doc])
  File "/mnt/d/Development_Source/app/.venv/lib/python3.10/site-packages/haystack_integrations/components/embedders/ollama/document_embedder.py", line 139, in run
    embeddings, meta = self._embed_batch(
  File "/mnt/d/Development_Source/app/.venv/lib/python3.10/site-packages/haystack_integrations/components/embedders/ollama/document_embedder.py", line 109, in _embed_batch
    result = response.json()
  File "/mnt/d/Development_Source/app/.venv/lib/python3.10/site-packages/requests/models.py", line 971, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Extra data: line 2 column 1 (char 98)

#####################################################################

**To Reproduce**
Assuming a Docker instance running Ollama is present, running the following python code results in the error on line 19 (note generation of the response to the OllamaGenerator prompt is successful):
#################################################################################
from haystack_integrations.components.generators.ollama import OllamaGenerator
llamagenerator = OllamaGenerator(model="orca-mini",
                            url = "http://localhost:11434/api/generate",
                            generation_kwargs={
                              "num_predict": 100,
                              "temperature": 0.9,
                              })

print(llamagenerator.run("Who is the best American actor?"))

from haystack import Document
from haystack_integrations.components.embedders.ollama import OllamaDocumentEmbedder

doc = Document(content="What do llamas say once you have thanked them? No probllama!")
document_embedder = OllamaDocumentEmbedder(model="orca-mini",
                        url = "http://localhost:11434/api/generate")

result = document_embedder.run([doc])

print(result['documents'][0].embedding)
###################################################

**Describe your environment (please complete the following information):**
 - OS: Windows 11, running WSL2 (Ubuntu 22.04)
 - Haystack version: 2.2.4
 - Integration version: Ollama-haystack 0.0.7

**Comment by cythaletheon** [comment]
Sorry never mind - I have realised I used the wrong API address - should be api/embeddings not api/generate.
Any chance the OllamaDocumentEmbedder could be enhanced to trap bleedingly obvious errors? :)
